# docker-compose.yml
version: "3.8"

services:
  {{ project_name }}:
    image: {{ docker_registry }}/{{ author_name | lower }}/{{ project_name | lower }}:latest
    container_name: {{ project_name }}
